config/routes.rb
Rails.application.routes.draw do
  resources :businesstypes do
    resources :businesses
  end
end

app/models/business.rb
class Business < ActiveRecord::Base
  belongs_to :businesstype

  validates :address, :presence => true
  validates :phone_number, :presence => true
  validates :website_address, :presence => true
  validates :hours_of_operation, :presence => true
end

app/models/businesstype.rb
class Businesstype < ActiveRecord::Base
  has_many :businesses

  validates :category, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  def new
    @businesstype = Businesstype.find(params[:businesstype_id])
    @business = @businesstype.businesses.new
  end

  def create
    @businesstype = Businesstype.find(params[:businesstype_id])
    @business = @businesstype.businesses.new(business_params)
    if @business.save
      redirect_to businesstype_path(@businesstype)
    else
      render :new
    end
  end

  def show
    @businesstype = Businesstype.find(params[:businesstype_id])
    @business = @businesstype.businesses.find(params[:id]) 
  end

private
  def business_params
    params.require(:business).permit(:name, :address, :phone_number, :website_address, :hours_of_operation)
  end
end

app/controllers/businesstypes_controller.rb
class BusinesstypesController < ApplicationController
  def index
    @businesstypes = Businesstype.all
    render :index
  end

  def show
    @businesstype = Businesstype.find(params[:id])
    render :show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/businesses/_form.html.erb
<%= render "layouts/errors", :object => @business %>

<%= form_for [@businesstype, @business] do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :address %>
<%= f.text_field :address %>
<%= f.label :hours_of_operation %>
<%= f.text_field :hours_of_operation %>
<%= f.label :website_address %>
<%= f.text_field :website_address %>
<%= f.label :phone_number %>
<%= f.text_field :phone_number %><br>
<%= f.submit %>
<% end %>

app/views/businesses/new.html.erb
<h1>New Business for <%=@businesstype.category %></h1>

<%= render 'form' %>

app/views/businesses/show.html.erb
<h1><%= @business.name %></h1>

<p><%= @business.address %></p>
<p><%= @business.phone_number %></p>
<p><%= @business.website_address %></p>
<p><%= @business.hours_of_operation %></p>

<p>Back to <%= link_to @businesstype.category, businesstype_path(@businesstype) %></p>

app/views/businesstypes/index.html.erb
<h1>Select a business type</h1>

<ul>
  <% @businesstypes.each do |businesstype| %>
    <li><%= link_to businesstype.category, businesstype_path(businesstype) %></li>
  <% end %>
</ul>

app/views/businesstypes/show.html.erb
<h1><%= @businesstype.category %></h1>

<%= link_to "Add a business", new_businesstype_business_path(@businesstype) %>

<ul>
<% @businesstype.businesses.each do |business| %>
  <li>
  <%= link_to business.name + ", " + business.address, businesstype_business_path(@businesstype, business) %>
  </li>
<% end %>
</ul>

<p>Back to <%= link_to "Categories", businesstypes_path %></p>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>Please fix these errors:</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wikipages</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>